# -*- coding: utf-8 -*-
"""Data-normalize.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xwBtGEZUVtQTTov2FKlGlrScPcKOW5W_
"""

###Clean cleaned_data_for_male_life_expectancy_2000_18cleaned_data_for_male_life_expectancy_2000_18.csv
def filenormalize(filename):
  import pandas as pd

  df = pd.read_csv('sample_data/'+filename+'.csv')
  cols = df.columns
  maxnum=[]
  for i in range(len(cols)):
    maxnum.append(df[cols[i]].max())
    temp = list(df[cols[i]])
  normalizval = max(maxnum)
  print(f"max value to be used for normalizing is {max(maxnum)} and its coordinates are column: {temp.index(max(temp))} row: {maxnum.index(max(maxnum))} for {filename}")
  # max value to be used for normalizing is 83.9 and its coordinates are column: 30 row: 18 

  f = open("sample_data/normalized"+filename+".csv", 'w')
  for i in range(len(cols)):
    z=cols[i]
    z= z.split('.')
    # # print(z)
    # z = '.'.join(z[:2])
    # print(z)
    # j=float(z)/float(normalizval)
    if(i==0):
      # print(z)
      f.write(str(z[0]))
    else:
      f.write(","+str(z[0]))
  f.write("\n")
  print(len(df.iloc[:,0]))
  for i in range(len(df.iloc[:,0])):
    for jj in range(len(cols)):
      # print(df.iloc[i][j])
      j=float(df.iloc[i][jj])/float(normalizval)
      if(jj==0):
        f.write(str(j))
      else:
        f.write(","+str(j))
    f.write("\n")
  f.close()
filenormalize("cleaned_data_for_male_life_expectancy_2000_18")
filenormalize("cleaned_data_for_male_at_65_life_expectancy_2002_18")
filenormalize("cleaned_data_for_female_life_expectancy_2000_18")

